include_user_id: False
use_id: "sid"

# model training
flag_add_input_embedding: False
flag_use_output_embedding: False

embedding_loss_weight: 0
sid_loss_weight: 1

evaluation_method: "default"

embedding_head_dict:
  use_new_init: False
  embed_target: ground_truth
  embed_proj_type: mlp
  text_embedding_dim: 768
  hidden_sizes: [256, 512, 768]
  embd_proj_dropout_rate: 0.5
  embd_proj_in_dropout_rate: 0.2

